version: '3.8'
services:
  toapi:
    image: toapi
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--brokers"
      - "${BROKERS}"
      - "--topic"
      - "${TOPIC_DOCUMENT}"
      - "--group-id"
      - "${TOAPI_CONSUMER_GROUP}"
    ports:
      - '3003:3003'
    extra_hosts: 
      - host.docker.internal:host-gateway
    volumes:
      - ./auth:/app/auth

  notifier:
    image: notifier
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--brokers"
      - "${BROKERS}"
      - "--topic"
      - "${TOPIC}"
      - "--group-id"
      - "${NOTIFIER_CONSUMER_GROUP}"
      - "--notifications-host"
      - "${NOTIFIER_NOTIFICATIONS_HOST}"
    extra_hosts: 
      - host.docker.internal:host-gateway
    volumes:
      - ./auth:/app/auth
