version: '3.8'
services:
  toapi:
    image: dclandau/cec-test-to-api
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--brokers"
      - "${BROKERS}"
      - "--topic"
      - "${TOPIC_DOCUMENT}"
      - "--group-id"
      - "${TOAPI_CONSUMER_GROUP}"
      - "--token"
      - "${NOTIFIER_TOKEN}"
    ports:
      - '3003:3003'
    extra_hosts: 
      - host.docker.internal:host-gateway
    environment: 
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5
    volumes:
      - ./auth:/app/auth

  notifier:
    image: dclandau/cec-notifier
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--brokers"
      - "${BROKERS}"
      - "--topic"
      - "${TOPIC}"
      - "--group-id"
      - "${NOTIFIER_CONSUMER_GROUP}"
      - "--notifications-host"
      - "${NOTIFIER_NOTIFICATIONS_HOST}"
    extra_hosts: 
      - host.docker.internal:host-gateway
    environment: 
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5
    volumes:
      - ./auth:/app/auth
